# Generated by Django 5.2.5 on 2025-08-30 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio_id', models.IntegerField()),
                ('municipio_nombre', models.CharField(choices=[('Barbosa', 'Barbosa'), ('Copacabana', 'Copacabana'), ('Girardota', 'Girardota'), ('Bello', 'Bello'), ('Medellín', 'Medellín'), ('Envigado', 'Envigado'), ('Itagüí', 'Itagüí'), ('Sabaneta', 'Sabaneta'), ('La Estrella', 'La Estrella'), ('Caldas', 'Caldas')], max_length=20)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('categoria', models.CharField(choices=[('Jardinería', 'Jardinería'), ('Limpieza', 'Limpieza'), ('Piscinero', 'Piscinero'), ('Carpintería', 'Carpintería'), ('Mantenimiento', 'Mantenimiento'), ('Plomería', 'Plomería')], max_length=20)),
                ('precio_referencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('personas_requeridas', models.PositiveIntegerField()),
                ('detalle_requerimiento', models.TextField(max_length=500)),
                ('visible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField()),
                ('empleador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
    ]
