# Generated by Django 5.2.5 on 2025-08-30 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Solo se permiten letras y espacios')])),
                ('apellidos', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Solo se permiten letras y espacios')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^(?:\\+57)?3\\d{9}$', 'Formato de teléfono inválido')])),
                ('password_hash', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('rol', models.CharField(choices=[('empleado', 'Empleado'), ('empleador', 'Empleador')], max_length=10)),
                ('municipio', models.CharField(choices=[('barbosa', 'Barbosa'), ('copacabana', 'Copacabana'), ('girardota', 'Girardota'), ('bello', 'Bello'), ('medellin', 'Medellín'), ('envigado', 'Envigado'), ('itagui', 'Itagüí'), ('sabaneta', 'Sabaneta'), ('la_estrella', 'La Estrella'), ('caldas', 'Caldas')], max_length=20)),
                ('direccion', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s]+$', 'No se permiten caracteres especiales')])),
                ('seguridad_social_nombre', models.CharField(max_length=100)),
                ('seguridad_social_estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
